# Generated by Django 3.1.14 on 2022-01-27 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='creation_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 27, 12, 30, 47, 866945)),
        ),
    ]
