# Generated by Django 3.1.14 on 2022-01-28 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0002_auto_20220127_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='creation_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 28, 21, 28, 53, 318321)),
        ),
    ]
