# Generated by Django 3.1.14 on 2022-01-27 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0001_initial'),
        ('vacancy_responce', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VacanceResponce',
            new_name='VacancyResponce',
        ),
    ]
